//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchAzaliya.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icons
    {
        public int Id_Icon { get; set; }
        public byte[] Icon_Source { get; set; }
        public string Name_Icon { get; set; }
    
        public virtual WorkshopIcons WorkshopIcons { get; set; }
    }
}
